// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSYQcNgNKSWw9v-P0Ya4fVKVOuedAwSUE',
    appId: '1:104478368885:web:52e276a73aadceb2e9443c',
    messagingSenderId: '104478368885',
    projectId: 'chatty-4cd01',
    authDomain: 'chatty-4cd01.firebaseapp.com',
    storageBucket: 'chatty-4cd01.firebasestorage.app',
    measurementId: 'G-QTYQTVRK3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxaqr4mc07aBaRjkx0_uMYnUUS0r1i4As',
    appId: '1:104478368885:android:e173bb4aebba2a2ae9443c',
    messagingSenderId: '104478368885',
    projectId: 'chatty-4cd01',
    storageBucket: 'chatty-4cd01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSZYeT8k1FisThFScu9sJMGqXLJbv_7c',
    appId: '1:104478368885:ios:a32c5704317d6fbbe9443c',
    messagingSenderId: '104478368885',
    projectId: 'chatty-4cd01',
    storageBucket: 'chatty-4cd01.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdSZYeT8k1FisThFScu9sJMGqXLJbv_7c',
    appId: '1:104478368885:ios:a32c5704317d6fbbe9443c',
    messagingSenderId: '104478368885',
    projectId: 'chatty-4cd01',
    storageBucket: 'chatty-4cd01.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSYQcNgNKSWw9v-P0Ya4fVKVOuedAwSUE',
    appId: '1:104478368885:web:94602b9aea93eee2e9443c',
    messagingSenderId: '104478368885',
    projectId: 'chatty-4cd01',
    authDomain: 'chatty-4cd01.firebaseapp.com',
    storageBucket: 'chatty-4cd01.firebasestorage.app',
    measurementId: 'G-CN5892V0Q1',
  );
}
